### ISSUE TITLE
"\xF0" from ASCII-8BIT to UTF-8"

### ISSUE THREAD

**Issue by luketeam5** [ntsd/jekyll-http-request#1]
Hello,

I am trying to retrieve a response from the Roblox API at this URL: https://games.roblox.com/v1/games?universeIds=2992873140. 

However, when I use the plugin to request the information, like this:
```
{{ 'https://games.roblox.com/v1/games?universeIds=2992873140' | http_request: 'GET', '', '' }}
```

I encounter an error during the build process that looks like this:

```
Jekyll::Converters::Markdown encountered an error while converting 'page.md':
                    "\xF0" from ASCII-8BIT to UTF-8
```

I have checked and made sure that the file is saved in UTF-8 without BOM. It seems like the issue might be related to the number at the end since when I remove it, everything works fine.

EDIT:
I belive it's related to the `0` at the end. When I change it to any other number the page converts fine.

I would appreciate any help you can provide. Thank you.

**Comment by ntsd** [comment]
> Hello,
> 
> I am trying to retrieve a response from the Roblox API at this URL: https://games.roblox.com/v1/games?universeIds=2992873140.
> 
> However, when I use the plugin to request the information, like this:
> 
> ```
> {{ 'https://games.roblox.com/v1/games?universeIds=2992873140' | http_request: 'GET', '', '' }}
> ```
> 
> I encounter an error during the build process that looks like this:
> 
> ```
> Jekyll::Converters::Markdown encountered an error while converting 'page.md':
>                     "\xF0" from ASCII-8BIT to UTF-8
> ```
> 
> I have checked and made sure that the file is saved in UTF-8 without BOM. It seems like the issue might be related to the number at the end since when I remove it, everything works fine.
> 
> EDIT: I belive it's related to the `0` at the end. When I change it to any other number the page converts fine.
> 
> I would appreciate any help you can provide. Thank you.

I think because the Ruby thinks it's ASCII-8BIT and try to convert to UTF-8 but it's already UTF-8

To fix this I think you can just do `force_encoding("UTF-8")` on the response body.

**Comment by ntsd** [comment]
@luketeam5 I had decided to force encoding to UTF-8 on the release 0.0.2.

So it should work now in 0.0.2 or later

https://github.com/ntsd/jekyll-http-request/commit/83ff760a864d7e671299139c3e7c4818640d6f44#diff-e0d529cf4bb375fcf1d68263a349307d80d2a4189c7506bbe25a31a87ae423bcR46

**Comment by luketeam5** [comment]
Thank you for the quick fix!
